### ISSUE TITLE
V6 roadmap

### ISSUE THREAD

**Issue by ThaUnknown** [hayase-app/ui#485]
- [x] host UI on a web URL with local caching [service worker?], like what discord does
  - [x] implement on electron
  - [x] implement on capacitor 
  - [x] this means complete separation of UI from the rest of the app
  - [x] create an IPC schema #413 however requires custom lib as comlink can't do this
  - [x] allows to use SvelteKit/vite #470
- [x] miru background process https://github.com/ThaUnknown/miru/issues/414
- [ ] miru server process  https://github.com/ThaUnknown/miru/issues/414
- [ ] torrent concurrency
- [ ] log statistics

**Comment by ThaUnknown** [comment]
urql
